namespace PVZRHTools;

[Serializable]
public struct ModifierSaveModel
{
    public bool BuffRefreshNoLimit { get; set; }
    public bool UnlimitedRefresh { get; set; }
    public bool UnlimitedScore { get; set; }
    public bool CardNoInit { get; set; }
    public bool ChomperNoCD { get; set; }
    public bool SuperStarNoCD { get; set; }
    public bool AutoCutFruit { get; set; }
    public bool RandomCard { get; set; }
    public bool ClearOnWritingField { get; set; }
    public bool GaoShuMode { get; set; }
    public bool ClearOnWritingVases { get; set; }
    public bool ClearOnWritingZombies { get; set; }
    public bool ClearOnWritingMix { get; set; }
    public bool CobCannonNoCD { get; set; }
    public double Col { get; set; }
    public bool ColumnPlanting { get; set; }
    public bool ConveyBeltModify { get; set; }
    public List<int> ConveyBeltTypes { get; set; }
    public List<TravelBuffVM> Debuffs { get; set; }
    public List<TravelBuffVM> InvestBuffs { get; set; }
    public bool DeveloperMode { get; set; }
    public bool DevLour { get; set; }
    public bool Exchange { get; set; }
    public bool FastShooting { get; set; }
    public string FieldString { get; set; }
    public bool FreeCD { get; set; }
    public bool FreePlanting { get; set; }
    public double GameSpeed { get; set; }
    public bool GameSpeedEnabled { get; set; }
    public bool GarlicDay { get; set; }
    public double GloveFullCD { get; set; }
    public bool GloveFullCDEnabled { get; set; }
    public bool GloveNoCD { get; set; }
    public double HammerFullCD { get; set; }
    public bool HammerFullCDEnabled { get; set; }
    public bool HammerNoCD { get; set; }
    public bool WheelNoCD { get; set; }
    public bool HardPlant { get; set; }
    public bool ImmuneForceDeduct { get; set; }
    public bool CurseImmunity { get; set; }
    public bool CrushImmunity { get; set; }
    public bool TrampleImmunity { get; set; }
    public List<HotkeyUIVM> Hotkeys { get; set; }
    public bool HyponoEmperorNoCD { get; set; }
    public bool IsMindCtrl { get; set; }
    public bool ItemExistForever { get; set; }
    public int ItemType { get; set; }
    public bool JackboxNotExplode { get; set; }
    public int LockBulletType { get; set; }
    public bool LockMoney { get; set; }
    public int LockPresent { get; set; }
    public int LockWheat { get; set; }
    public bool LockSun { get; set; }
    public bool MineNoCD { get; set; }
    public bool NeedSave { get; set; }
    public string NewLevelName { get; set; }
    public double NewMoney { get; set; }
    public double NewSun { get; set; }
    public double NewZombieUpdateCD { get; set; }
    public bool NoFail { get; set; }
    public bool NoHole { get; set; }
    public bool NoIceRoad { get; set; }
    public bool DisableIceEffect { get; set; }
    public bool UnlockRedCardPlants { get; set; }
    public bool PlantingNoCD { get; set; }
    public int PlantType { get; set; }
    public bool PlantUpgrade { get; set; }
    public bool PresentFastOpen { get; set; }
    public double Row { get; set; }
    public bool ScaredyDream { get; set; }
    public bool SeedRain { get; set; }
    public bool Shooting1 { get; set; }
    public bool Shooting2 { get; set; }
    public bool Shooting3 { get; set; }
    public bool Shooting4 { get; set; }
    public string ShowText { get; set; }
    public bool StopSummon { get; set; }
    public bool SuperPresent { get; set; }
    public double Times { get; set; }
    public bool TopMostSprite { get; set; }
    public bool EnableAnimations { get; set; }
    public bool IsDarkMode { get; set; }
    public List<TravelBuffVM> TravelBuffs { get; set; }
    public bool UltimateRamdomZombie { get; set; }
    public bool UltimateSuperGatling { get; set; }
    public bool AutoRhythmGame { get; set; }
    public bool UndeadBullet { get; set; }
    public bool OldObsidianBullet { get; set; }
    public bool UnlockAllFusions { get; set; }
    public string VasesFieldString { get; set; }
    public string ZombieFieldString { get; set; }
    public string MixFieldString { get; set; }
    public double ZombieSeaCD { get; set; }
    public bool ZombieSeaEnabled { get; set; }
    public bool ZombieSeaLowEnabled { get; set; }
    public List<int> ZombieSeaTypes { get; set; }
    public int ZombieType { get; set; }
    // PvE 斗蛐蛐布阵：盲盒僵尸置顶（-1 表示不置顶，沿用游戏原始随机）
    public int PvEBlindBoxZombie1 { get; set; }
    public int PvEBlindBoxZombie2 { get; set; }
    public int PvEBlindBoxZombie3 { get; set; }
    public int PvEBlindBoxZombie4 { get; set; }
    public int PvEBlindBoxZombie5 { get; set; }
    public int PvEBlindBoxZombie6 { get; set; }

    // 诸神：进化
    public bool GodEvolutionUnlimitedRefresh { get; set; }
    public bool GodEvolutionFreeUpgradeQuality { get; set; }
    public bool GodEvolutionLuckyEnabled { get; set; }
    public float GodEvolutionLucky { get; set; }
    public bool GodEvolutionDifficultyEnabled { get; set; }
    public int GodEvolutionDifficulty { get; set; }
    public bool GodEvolutionRefreshCountEnabled { get; set; }
    public int GodEvolutionRefreshCount { get; set; }
    public bool GodEvolutionMaxPlantCountEnabled { get; set; }
    public int GodEvolutionMaxPlantCount { get; set; }
    public bool GodEvolutionOptionCountEnabled { get; set; }
    public int GodEvolutionOptionCount { get; set; }
    public bool GodEvolutionUpgradeBuffChanceEnabled { get; set; }
    public int GodEvolutionUpgradeBuffChance { get; set; }
    public bool GodEvolutionSuperUpgrade { get; set; }
    public bool GodEvolutionForceSuperQuality { get; set; }
    public bool GodEvolutionUncrashable { get; set; }
    public bool GodEvolutionQualityWeightEnabled { get; set; }
    public float GodEvolutionQualityDefault { get; set; }
    public float GodEvolutionQualitySilver { get; set; }
    public float GodEvolutionQualityGold { get; set; }
    public float GodEvolutionQualityDiamond { get; set; }
    public bool GodEvolutionDamageMultiplierEnabled { get; set; }
    public float GodEvolutionDamageMultiplier { get; set; }
}